# Run on latest node image available
image: node

# Prevent gitlab from removing cached files on git clean
variables:
  GIT_CLEAN_FLAGS: -x -f -e **


######################################
#            G R O U P S             #
######################################

# Make jobs marked with group fi-runner run on shared fi machine
.fi-runner: &fi-runner
  tags:
    - shared-fi

# Run jobs on merge request
.mr-only: &mr-only
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# Run only on master
.master-only: &master-only
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'


######################################
#             C A C H E              #
######################################

# These folders are cached between builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .cache/
    - public/


######################################
#              J O B S               #
######################################

stages:
  - .pre
  - static-analysis
  - build
  - test

# Install npm modules and gatsby
npm:install:
  <<: *fi-runner
  stage: .pre
  script:
    - npm ci    
    - npm install gatsby-cli -g
    - npx gatsby -v

# Run eslint
eslint:
  <<: *fi-runner
  stage: static-analysis
  needs: ["npm:install"]
  script:
    - npm run lint

# Attempts to build the gatsby app
build:
  <<: *fi-runner
  stage: build
  needs: [eslint]
  script:
    - npm run build
  artifacts:
    paths:
      - public/

# Runs test
test:
  <<: *fi-runner
  stage: test
  needs: [build]
  script:
    - CI=true npm run test
