# Run on latest node image available
image: node

# Prevent gitlab from removing cached files on git clean
variables:
  GIT_CLEAN_FLAGS: -x -f -e **


######################################
#            G R O U P S             #
######################################

# Make jobs marked with group fi-runner run on shared fi machine
.fi-runner: &fi-runner
  tags:
    - shared-fi

# Run always, commits, merge request and on master
.run-always: &run-always
  rules:
    - when: always

# Run jobs on merge request
.mr-only: &mr-only
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# Run manually only on master
.master-manual: &master-manual
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
      allow_failure: true


######################################
#             C A C H E              #
######################################

# These folders are cached between builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .cache/
    - public/


######################################
#              J O B S               #
######################################

stages:
  - .pre
  - static-analysis
  - build
  - test
  - deploy

# Display node and npm version
before_script:
  - node -v
  - npm -v

# Install npm modules and gatsby
npm:install:
  <<: *fi-runner
  <<: *run-always
  stage: .pre
  script:
    - npm ci    
    - npm install gatsby-cli -g
    - npx gatsby -v

# Run eslint
eslint:
  <<: *fi-runner
  <<: *run-always
  stage: static-analysis
  needs: ["npm:install"]
  script:
    - npm run lint

# Attempts to build the gatsby app
build:
  <<: *fi-runner
  <<: *mr-only
  stage: build
  needs: [eslint]
  script:
    - npm run build

# Runs test
test:
  <<: *fi-runner
  <<: *mr-only
  stage: test
  needs: [build]
  script:
    - CI=true npm run test

# Build and deploy on master only
pages:
  <<: *fi-runner
  <<: *master-manual
  stage: deploy
  needs: [eslint]
  script:
    - npm run build -- --prefix-paths
  artifacts:
    paths:
      - public/
